### ISSUE TITLE
can't decompress chinese

### ISSUE THREAD

**Issue by bluelovers** [remusao/mono#213]
```ts
const { compress, decompress } = require('@remusao/smaz');

let str = `Next.js踩坑入门系列（一）— Hello Next.js!`;

let c = compress(str);
let d = decompress(c);
let b = Buffer.from(str)

console.dir({
	b,
	c,
	d,
})
```

`d` => `Next.js)Qeèû\x17\b\x00\t\x14 Hello Next.js!`

**Comment by remusao** [comment]
Hi @bluelovers,

Thanks for taking the time to open an issue. I have to admit that the documentation of `@remusao/smaz` is lacking, at best. I will try to write a proper README.md soon. The issue is that for performance reasons, only ASCII strings are supported by the library at the moment (to save some conversion to a different format). To make it work for any unicode strings, I would suggest to use something like `punycode` first (or another conversion from Unicode to ASCII). I have modified your example in the following way:

```js
const { compress, decompress } = require("@remusao/smaz");
const { encode, decode } = require('punycode');

let str = `Next.js踩坑入门系列（一）— Hello Next.js!`;

let c = compress(encode(str)); // NOTE: here we `encode` str before compression.
let d = decompress(c);
let b = decode(d); // NOTE: we `decode` the decompressed version.

console.dir({
  check: b === str, // NOTE: here `b` and `str` are identical.
  b,
  c,
  d,
});
```
